[build]
  base = "rm_client_portal_fe"
  command = "quasar build"
  publish = "dist/spa"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- rm_client_portal_fe/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200